### ISSUE TITLE
Erroneous definition of the Lagrangian

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/NLPModels.jl#108]
With general constraints defined [like this](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blame/master/docs/src/index.md#L30), the following Lagrangian should contain terms with both *c(x) - cL* and *cU - c(x)*.

**Comment by abelsiqueira** [comment]
We wrote the Lagrangian that way because of CUTEst, but it is a little misleading calling it the Lagrangian.

Only `hess`-related functions use the Lagrangian, so it is better to have the form `f(x) + c(x)'*y`. I think that we should remove mention of the Lagrangian and leave the API doing what it already does. The Lagrangian definition also uses zL and zU but it isn't used anywhere.

**Comment by abelsiqueira** [comment]
Anything we can do on this one, or should we close it?
