### ISSUE TITLE
Enforce structure (nnzj and nnzh) on jac_coord and hess_coord

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModels.jl#155]

**Comment by abelsiqueira** [comment]
On `MathProgNLPModel` (and possibly other places), `hess_coord` has repeated elements, so `nnzh` is not really the number of nonzeros in the Hessian, but the length of the vector necessary to store the output.
Should we do something about this?
- Removing repeated elements may be too expensive (`sparse(I, J, V)` accepts repeated elements);
- Change the names `nnzX` to something else.
- Create something else to store the current `nnzh` and compute the correct `nnzh` (needed for something?)

**Comment by dpo** [comment]
Most implementations of the sparse coordinate format accept repeated elements because they occur naturally in sparse problems (e.g., finite elements but also optimization). The entries are simply summed. I think our `nnzh` should stay faithful to what the modeling language provides (AMPL, CUTEst, JuMP or ForwardDiff). Maybe we should just change the documentation of `nnzh` and `nnzj` to say they may count repeated entries?!

**Comment by abelsiqueira** [comment]
Agreed, much better.
