### ISSUE TITLE
Extension of NLPModels to Maximum and Quasi Likelihood Estimation

### ISSUE THREAD

**Issue by finmod** [JuliaSmoothOptimizers/NLPModels.jl#171]
@abelsiqueira Nice work. 
Are you considering extending your NLP models to maximum likelihood and quasi-likelihood estimation? It would be nice.

The standard reference that mirrors most of your functions can be found in Chapter 2 of Seber and Wild, Nonlinear Regression, 2003. Also Chapter 14 of Kenneth Lange, Numerical Analysis for Statisticians, 2nd ed, 2010

A good test NLP can be found here: https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/ode_lorentz_attractor.jl . for alternative optimizers.

**Comment by abelsiqueira** [comment]
Thanks, it should be possible to extend to maximum likelihood without much trouble, and it is something I considered as a possible application, but we're really swamped right now. If you, or anyone else, would like to take the project, I'll be happy to help. Otherwise, I'll have to wait for a student interested in the subject.

**Comment by abelsiqueira** [comment]
Started a related project here: https://github.com/CiDAMO/MultObjNLPModels.jl/

**Comment by abelsiqueira** [comment]
I'll be closing this since there's been no interest for a while and this package became Core API and tools.
