### ISSUE TITLE
LLSModel  hess_structure! not implemented

### ISSUE THREAD

**Issue by vepiteski** [JuliaSmoothOptimizers/NLPModels.jl#273]
Code compiled using 0.10.0 but now fails under 0.12.2. The following reproduces the bug.
   ```
   Z = rand (3,2)
    v = rand(3)
    model = LLSModel(Z,v)
    hess(model,zeros(2)
```

**Comment by dpo** [comment]
After fixing the space and the missing parenthesis, I can reproduce:
```julia
julia> Z = rand(3,2)
3×2 Array{Float64,2}:
 0.192139  0.0255131
 0.200331  0.834181
 0.922048  0.0507972

julia> v = rand(3)
3-element Array{Float64,1}:
 0.8408910607392606
 0.6059698898065355
 0.9778873390538139

julia> model = LLSModel(Z,v)
LLSModel(Minimization problem generic-LLSModel
nvar = 2, ncon = 0 (0 linear)
, NLSMeta(3, 2, [0.0, 0.0], 6, 0), NLSCounters(Counters(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), 0, 0, 0, 0, 0, 0, 0), [1, 2, 3, 1, 2, 3], [1, 1, 1, 2, 2, 2], [0.
1921388691974788, 0.200330553691759, 0.9220480461636273, 0.025513079730938415, 0.8341806745176974, 0.050797210586230435], [0.8408910607392606, 0.6059698898065355, 0.9778873390538139], Int64[], Int64[], Float64[])

julia> hess(model,zeros(2))
ERROR: hess_structure! not implemented
Stacktrace:
 [1] hess_structure!(::LLSModel, ::Array{Int64,1}, ::Array{Int64,1}) at /Users/dpo/dev/julia/JSO/NLPModels.jl/src/NLPModels.jl:443
 [2] hess_structure(::LLSModel) at /Users/dpo/dev/julia/JSO/NLPModels.jl/src/NLPModels.jl:435
 [3] #hess#106(::Float64, ::typeof(hess), ::LLSModel, ::Array{Float64,1}) at /Users/dpo/dev/julia/JSO/NLPModels.jl/src/NLPModels.jl:505
 [4] hess(::LLSModel, ::Array{Float64,1}) at /Users/dpo/dev/julia/JSO/NLPModels.jl/src/NLPModels.jl:505
 [5] top-level scope at REPL[67]:1
```

**Comment by abelsiqueira** [comment]
This is related to a change we did last week, in which LLS was changed to store the triplet format. To figure out the `hess` structure we'd need to compute the product `A' * A` at construction time, so it would be a large overhead to do it properly. Do you need `hess` explicitly?

**Comment by vepiteski** [comment]
Yes, I use a LLS as a simple example in a course. I show how to solve it as a quadratic optimization model using the linear conjugate gradient given its matrix Q. Is it possible to obtain a LinearOperator Q instead of the matrix Q? It would be even more pedagogical!

**Comment by dpo** [comment]
Maybe you could say that it's a bad idea to use CG on A'A and use CGLS? :-)

**Comment by abelsiqueira** [comment]
Yes, you can also use the CG for LS problems from Krylov.
```julia
using Krylov
...
model = LLSModel(Z,v)
x = model.meta.x0
Krylov.cg(hess_op(model, x), grad(model, x))
```
or
```
Krylov.cgls(jac_residual(model, x), residual(model, x)) # jac_op_residual can also be used.
```

**Comment by abelsiqueira** [comment]
And https://github.com/JuliaSmoothOptimizers/QuadraticModels.jl is being prepared for release as well.

**Comment by vepiteski** [comment]
A further thought: it is legit to call hess(model) and frustrating to bump with an error. Why not use the **memoisation** technique  (see [this discussion](https://stackoverflow.com/questions/52050262/how-to-do-memoization-or-memoisation-in-julia-1-0) ) to compute hess_structure at most once if ever required? No efficiency penalty would be incurred unless the user requires a hess.

**Comment by abelsiqueira** [comment]
For efficient use of the Hessian in coordinate format, we need to inform the user of the number of nonzeros in the Hessian before the function call - for instance, he wants to allocate the arrays and call the in-place functions - so it has to be calculated during the construction of `NLPModelMeta`. It should be feasible to create different LLS models, such as `LLSMatrixModel`, `LLSCoordModel` and `LLSOperatorModel` defined by the input type on `LLSModel`. For this example, `LLSMatrixModel` could have `hess` defined.

**Comment by vepiteski** [comment]
> For efficient use of the Hessian in coordinate format, we need to inform the user of the number of nonzeros in the Hessian before the function call - for instance, he wants to allocate the arrays and call the in-place functions - so it has to be calculated during the construction of `NLPModelMeta`. 

Why not defer this calculation to the first call to hess_structure? This could default to full matrix at construction time so that hess could be called without error message. Or have a default version of hess_structure! which gives a full matrix, and let the user override this default version when needed?

>It should be feasible to create different LLS models, such as `LLSMatrixModel`, `LLSCoordModel` and `LLSOperatorModel` defined by the input type on `LLSModel`. For this example, `LLSMatrixModel` could have `hess` defined.

Code duplication for efficiency purposes does not appeal to me.

**Comment by dpo** [comment]
It's easy to implement your own hess:
```
function NLPModels.hess(model::LLSModel, x::AbstractVector; obj_weight::Real=one(eltype(x)))
    @lencheck model.meta.nvar x
    J = jac_residual(model, x)
    return obj_weight * (J' * J)
end

function NLPModels.hess_op(model::LLSModel, x::AbstractVector; obj_weight::Real=one(eltype(x)))
    @lencheck model.meta.nvar x
    J = jac_op(model, x)
    return obj_weight * J' * J
end
```
I'm not sure we should implement it by default because it would be quite inefficient for general problems.

**Comment by chenwilliam77** [comment]
Hi there, I really appreciate all the cool work your group has been doing on providing these models and interfaces with optimizers. I see that there's been some work on this error, so I understand you're likely still in the middle of figuring out how to handle it. I just wanted to point out one nice use case that has been triggering this error for me is replicating MATLAB's lsqlin function in Julia. I want to use your LLSModel (or the coming QuadraticModel) with your wrapper for Ipopt, but when doing so, I run into the error of `hess_structure! not implemented`. I tried adding manually the functions provided by @dpo (see below), but that didn't work either.

> It's easy to implement your own hess:
> 
> ```
> function NLPModels.hess(model::LLSModel, x::AbstractVector; obj_weight::Real=one(eltype(x)))
>     @lencheck model.meta.nvar x
>     J = jac_residual(model, x)
>     return obj_weight * (J' * J)
> end
> 
> function NLPModels.hess_op(model::LLSModel, x::AbstractVector; obj_weight::Real=one(eltype(x)))
>     @lencheck model.meta.nvar x
>     J = jac_op(model, x)
>     return obj_weight * J' * J
> end
> ```
> 
> I'm not sure we should implement it by default because it would be quite inefficient for general problems.


It all works using ADNLSModel, but I presume there may be some speed gains by treating the linear least squares case on its own.

**Comment by abelsiqueira** [comment]
Instead of `hess`, you would need `hess_structure!` and `hess_coord!` functions for Ipopt. These functions should deal only with the nonzero elements, so there will be speed gains mainly if your matrices are sparse. I have started implementing a variant https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/282 that implements `hess_structure!` and `hess_coord!` for dense matrices. You can copy them and they should be sufficient for now.

What kind of constraints do you have in your Least squares model?

**Comment by chenwilliam77** [comment]
In the use cases that I have, I am not placing any bounds on `x` (where I have the objective `||A * x - b||^2 / 2`, but I have inequality and equality constraints of the form `a <= C * x <= b`. Since I'm trying to match MATLAB's lsqlin, the constraints have the form (in Julia) `-Inf <= C1 * x <= ucon1` and `ucon2 <= C2 *x = ucon2`. To add them to the `LLSModel`, I concatenate the `C1` and `C2 matrices, as well as the respective `lcon` and `ucon` bounds.

The matrices are indeed sparse, so I hope there are indeed speed gains. I'll take a look and test out what you have!

**Comment by dpo** [comment]
@chenwilliam77 I was thinking of submitting a pull request to NLPModelsIpopt to automatically transform any least-squares problem to what we call ["feasibility form"](https://juliasmoothoptimizers.github.io/NLPModels.jl/stable/models/#FeasibilityFormNLS-1), which means that the least-squares residual is moved to the constraints. IPOPT should be happier that way because A'A will never appear. However, you can easily try that yourself by calling `ipopt(FeasibilityFormNLS(model))` where `model` is your current model.

On a different note, can I ask where your problems come from? I'm looking for interesting linear least-squares problems with linear equality constraints (only). If you have some that you are willing/able to share, I would be interested.

**Comment by abelsiqueira** [comment]
Thanks for explaining. Your use case is different from the originally posted but has a similar issue. It breaks in a different way, though.

@dpo, I was gonna send a similar thing, but you beat me to it. It's currently not enough to use `FeasibilityFormNLS` because of the constraints: https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/master/src/feasibility_form_nls.jl#L198-L213

This could probably be improved so a FeasibilityFormNLS of an LLSModel is a little bit smarter, or it could mean that we should implement `hess`-related functions to sparse `A` (meaning computing the expensive `A'*A`).

**Comment by chenwilliam77** [comment]
> On a different note, can I ask where your problems come from? I'm looking for interesting linear least-squares problems with linear equality constraints (only). If you have some that you are willing/able to share, I would be interested.

@dpo I am in the middle of trying to translate portions of [SLM](https://www.mathworks.com/matlabcentral/fileexchange/24443-slm-shape-language-modeling), which is useful in the context of economics when solving a fixed point problem that emerges from a dynamic programming problem. In particular, using a least-squares spline to represent the function on which I am iterating is desirable because I can preserve properties like monotonicity and concavity.

With regard to problems with only linear equality constraints, I believe the base case of a least-squares spline that just requires C2 continuity will only have equality constraints.

**Comment by dpo** [comment]
I would like to see a situation where there's an advantage to working with A'A though. I only know disadvantages.

**Comment by chenwilliam77** [comment]
@dpo This may be a peculiarity with the problem I'm solving, but I actually get a roughly 30ms slowdown when calling `ipopt(FeasibilityFormNLS(model))` instead of `ipopt(model)`, where `model` is a `ADNLSModel`.

**Comment by dpo** [comment]
That's a useful data point, thank you. It's probably the fault of our FeasibilityFormNLS that should be improved. This form leads to larger linear systems inside IPOPT but they should generally be sparser.

**Comment by abelsiqueira** [comment]
Moved to https://github.com/JuliaSmoothOptimizers/LLSModels.jl/issues/2
